class FactoryError(Exception): ...
class AssociatedClassError(FactoryError): ...
class UnknownStrategy(FactoryError): ...
class UnsupportedStrategy(FactoryError): ...
class CyclicDefinitionError(FactoryError): ...
class InvalidDeclarationError(FactoryError): ...
