from . import declarations as declarations
from _typeshed import Incomplete
from collections.abc import Generator

class Faker(declarations.BaseDeclaration):
    provider: Incomplete
    def __init__(self, provider, **kwargs) -> None: ...
    def evaluate(self, instance, step, extra): ...
    @classmethod
    def override_default_locale(cls, locale) -> Generator[None, None, None]: ...
    @classmethod
    def add_provider(cls, provider, locale: Incomplete | None = ...) -> None: ...
