from _typeshed import Incomplete

def import_object(module_name, attribute_name): ...

class log_pprint:
    args: Incomplete
    kwargs: Incomplete
    def __init__(self, args=..., kwargs: Incomplete | None = ...) -> None: ...

class ResetableIterator:
    iterator: Incomplete
    past_elements: Incomplete
    next_elements: Incomplete
    def __init__(self, iterator, **kwargs) -> None: ...
    def __iter__(self): ...
    def reset(self) -> None: ...

class OrderedBase:
    CREATION_COUNTER_FIELD: str
    def __init__(self, **kwargs) -> None: ...
    def touch_creation_counter(self) -> None: ...

def sort_ordered_objects(items, getter=...): ...
